[package]
name = "SionFlowRT"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
naga = "28.0.0"
petgraph = "0.8.3"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tera = "1.20.1"
